# Generated by Django 5.1.7 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='trailer_url',
            field=models.URLField(help_text='YouTube or Vimeo video URL'),
        ),
    ]
